<main>
    <div class="container" id="container">

      <section class="section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4">
        <div class="container">
          <div class="row justify-content-center">
            <div class="col-lg-4 col-md-6 d-flex flex-column align-items-center justify-content-center">

              <div class="d-flex justify-content-center py-4">
                <a href="/" class="logo d-flex align-items-center w-auto">
                  <img src="/app/assets/img/" alt="">
                  <span class="d-none d-lg-block">Sita</span>
                </a>
              </div><!-- End Logo -->

              <div class="card mb-3">

                <div class="card-body">

                  <div class="pt-4 pb-2">
                    <h5 class="card-title text-center pb-0 fs-4">Entrar na sua conta</h5>
                    <p class="text-center small">Digite seu nome de usuário e senha para entrar</p>
                  </div>

                  <form id="form" method="post" class="row g-3 needs-validation" novalidate>

                    <div class="col-12">
                      <label for="yourUsername" class="form-label">Username</label>
                      <div class="input-group has-validation">
                        <span class="input-group-text" id="inputGroupPrepend">@</span>
                        <input type="text" name="email" class="form-control" id="yourUsername" required>
                        <div class="invalid-feedback">Escolha um nome de usuário.</div>
                      </div>
                    </div>

                    <div class="col-12">
                      <label for="yourPassword" class="form-label">Senha</label>
                      <input type="password" name="senha" class="form-control" id="yourPassword" required>
                      <div class="invalid-feedback">Escolha um nome de usuário.</div>
                    </div>
                    <div class="col-12">
                      <button id="btnSubmit" class="btn btn-primary w-100">Entar</button>
                    </div>
                    <div class="col-12">
                      <p class="small mb-0">Não possui conta? <a href="/registrar">Crie uma conta</a></p>
                    </div>
                    <small id="small" class='form-text text-success'><?= isset($_GET['q']) ? $_GET['q']: "" ?></small>
                  </form>

                </div>
              </div>

              <div class="credits">
                Designed by <a href="#">Joel Malamba</a>
              </div>

            </div>
          </div>
        </div>

      </section>

    </div>
  </main><!-- End #main -->
  <div class="d-none" id="preloader"></div>
