<main id="main" class="main">

    <div class="pagetitle">
        <h1>Perguntas e Respostas</h1>
    </div><!-- End Page Title -->

    <section class="section dashboard">
        <div class="row">
            <div class="col-12">
                <div class="card top-selling overflow-auto">
                    <div class="card-header pb-2">
                        <form class="row g-3">
                            <div class="col-md-12">
                                <label class="form-label">Pesquisar</label>
                                <div class="input-group">
                                    <input type="text" class="form-control" id="pesquisa"
                                        placeholder="Pesquise pela sua dúvida" aria-label="Recipient's username"
                                        aria-describedby="basic-addon2">
                                    <button class="input-group-text" id="basic-addon2"
                                        onclick="filtarPorPesquisa()">Pesquisar</button>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <label class="form-label">Nível Académico</label>
                                <select class="form-select" id="nivel_academico_quest"
                                    aria-label="Default select example" onchange="filtarPorNivelAcademico()" required>
                                    <option selected="" value="">Selecionar</option>
                                    <option value="1">Ensino Médio</option>
                                    <option value="2">Ensino Superior</option>
                                    <option value="3">Mestrado/Pós-graduação</option>
                                    <option value="4">Formação Profissional</option>
                                </select>
                            </div>

                            <div class="col-md-6">
                                <label class="form-label">Aréa</label>
                                <select class="form-select" onchange="filtarPorAreaDeFormacao()"
                                    id="area_formacao_quest" aria-label="Default select example" required>
                                    <option selected="" value="">Selecionar</option>
                                    <option>Ciências Exatas</option>
                                    <option>Engenharia</option>
                                    <option>Tecnologias de Comunicação e Informação</option>
                                    <option>Ciências Biológicas</option>
                                    <option>Artes e Design</option>
                                    <option>Ciências Agrárias</option>
                                    <option>Ciências Ambientais</option>
                                    <option>Ciências Sociais Aplicadas</option>
                                    <option>Ciências Físicas e Biológicas</option>
                                    <option>Ciências Econômicas e Jurídicas</option>
                                </select>
                            </div>
                            <div class="col-md-4 d-none">
                                <label class="form-label">Ordenar por</label>
                                <select id="inputState" class="form-select">
                                    <option selected="">Calssificar por</option>
                                    <option>Mais recente</option>
                                    <option>Mais votado</option>
                                </select>
                            </div>
                        </form>
                    </div>
                    <div class="card-body pb-0">


                        <table class="table table-borderless">
                            <tbody id="body_questao">
                                <?php
                                if (count($this->view->questao) > 0) {

                                    foreach ($this->view->questao as $key => $value) { ?>
                                        <tr>
                                            <th scope="row" style="padding:10px; width:54px">
                                                <a href="/forumrespostas?id_pergunta=<?= $value['id_pergunta'] ?>">
                                                    <img src="/app/assets/img/<?= $value['img'] ?>" alt="">
                                                </a>
                                            </th>
                                            <td>
                                                <a href="/forumrespostas?id_pergunta=<?= $value['id_pergunta'] ?>"
                                                    class="text-primary fw-bold mb-1"><?= $value['questao'] ?></a>

                                                <?= substr($value['detalhes_questao'], 0, 100) . "..." ?>
                                                <br>
                                                <a href="/forumrespostas?id_pergunta=<?= $value['id_pergunta'] ?>"> Ler
                                                    mais</a>
                                            </td>
                                            <td class="fw-bold" style="white-space: nowrap;">
                                                Respostas
                                                (
                                                <?= $value['quantidade_respostas'] ?>)
                                            </td>
                                        </tr>
                                    <?php }
                                } else {
                                    echo "<h4 class='mt-2'>Nenhuma Informação Encontrada!<h4>";
                                } ?>

                            </tbody>
                        </table>

                    </div>

                    <div class="card-footer pb-2">
                        <a href="#" data-bs-toggle="modal" data-bs-target="#ExtralargeModal">Fazer uma pergunta</a>
                    </div>

                </div>

                <div class="modal fade" id="ExtralargeModal" tabindex="-1" aria-hidden="true" style="display: none;">
                    <div class="modal-dialog modal-xl">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title">Faça uma pergunta</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                    aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <form class="row g-3">
                                    <div class="col-md-12">
                                        <label class="form-label">Titulo</label>
                                        <input type="text" class="form-control" id="titulo"
                                            placeholder="Por Exemplo: Por que devemos criar um pré-projeto?">
                                    </div>
                                    <div class="col-md-6">
                                        <label class="form-label">Nível Académico</label>
                                        <select class="form-select" name="nivel_academico" id="nivel_academico_forum"
                                            aria-label="Default select example" required>
                                            <option selected="" value="">Selecionar</option>
                                            <option value="1">Ensino Médio</option>
                                            <option value="2">Ensino Superior</option>
                                            <option value="3">Mestrado/Pós-graduação</option>
                                            <option value="4">Formação Profissional</option>
                                        </select>
                                    </div>

                                    <div class="col-md-6">
                                        <label class="form-label">Aréa de Formação</label>
                                        <select class="form-select" name="area_formacao" id="area_formacao_forum"
                                            aria-label="Default select example" required>
                                            <option selected="" value="">Selecionar</option>
                                            <option>Ciências Exatas</option>
                                            <option>Engenharia</option>
                                            <option>Tecnologias de Comunicação e Informação</option>
                                            <option>Ciências Biológicas</option>
                                            <option>Artes e Design</option>
                                            <option>Ciências Agrárias</option>
                                            <option>Ciências Ambientais</option>
                                            <option>Ciências Sociais Aplicadas</option>
                                            <option>Ciências Físicas e Biológicas</option>
                                            <option>Ciências Econômicas e Jurídicas</option>
                                        </select>
                                    </div>
                                    <label class="form-label">Detalhes (Opcional)</label>
                                </form>

                                <!-- Quill Editor Default -->

                                <div class="quill-editor-default" id="detalhes_pergunta">
                                    <p>Hello World!</p>
                                    <p>This is Quill <strong>default</strong> editor</p>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" id="fechar_form"
                                    data-bs-dismiss="modal">Fechar</button>
                                <button type="button" class="btn btn-primary"
                                    onclick="fazerPerguntaForum(<?= $_SESSION['id'] ?>, '<?= $_SESSION['img'] ?>')">Salvar</button>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
    </section>
</main>