<main id="main" class="main">

    <div class="pagetitle">
        <h1>Editar Perfil</h1>
    </div><!-- End Page Title -->

    <section class="section profile">
        <div class="row">
            <div class="col-xl-4">

                <div class="card">
                    <div class="card-body profile-card pt-4 d-flex flex-column align-items-center">

                        <img src="/app/assets/img/<?= $_SESSION['img'] ?>" width="250" height="140" alt="Profile"
                            class="rounded-circle">
                        <h2>
                            <?= $_SESSION['nome'] ?>
                        </h2>

                        <div class="social-links mt-2">
                            <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
                            <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
                            <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
                            <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
                        </div>
                    </div>
                </div>

            </div>

            <div class="col-xl-8">

                <div class="card">
                    <div class="card-body pt-3">
                        <!-- Bordered Tabs -->
                        <ul class="nav nav-tabs nav-tabs-bordered">

                            <li class="nav-item">
                                <button class="nav-link active" data-bs-toggle="tab"
                                    data-bs-target="#profile-overview">Sobre Mim</button>
                            </li>

                            <li class="nav-item">
                                <button class="nav-link" data-bs-toggle="tab" data-bs-target="#profile-edit">Editar
                                    Perfil</button>
                            </li>

                            <li class="nav-item">
                                <button class="nav-link" data-bs-toggle="tab"
                                    data-bs-target="#profile-change-password">Mudar Password</button>
                            </li>

                        </ul>
                        <div class="tab-content pt-2">

                            <div class="tab-pane fade show active profile-overview" id="profile-overview">
                                <h5 class="card-title">Detalhes do Perfil</h5>

                                <div class="row">
                                    <div class="col-lg-3 col-md-4 label ">Nome Completo</div>
                                    <div class="col-lg-9 col-md-8">
                                        <?= $this->view->user[0]['nome'] ?>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-lg-3 col-md-4 label">Instituição</div>
                                    <div class="col-lg-9 col-md-8">
                                        <?= $this->view->user[0]['instituicao'] ?>
                                    </div>
                                </div>


                                <div class="row">
                                    <div class="col-lg-3 col-md-4 label">Telefone</div>
                                    <div class="col-lg-9 col-md-8">
                                        <?= $this->view->user[0]['telefone'] ?>
                                    </div>
                                </div>
                            </div>

                            <div class="tab-pane fade profile-edit pt-3" id="profile-edit">
                                <!-- Profile Edit Form -->
                                <form action="/editar" enctype="multipart/form-data" method="post">
                                    <div class="row mb-3">
                                        <label for="profileImage" class="col-md-4 col-lg-3 col-form-label">Profile
                                            Image</label>
                                        <div class="col-md-8 col-lg-9">
                                            <img src="/app/assets/img/<?= $_SESSION['img'] ?>" height="120"
                                                alt="Profile">
                                            <div class="pt-2">
                                                <a href="#" class="btn btn-primary btn-sm"
                                                    title="Upload new profile image"><i class="bi bi-upload"></i></a>
                                                <a href="#" class="btn btn-danger btn-sm"
                                                    title="Remove my profile image"><i class="bi bi-trash"></i></a>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row mb-3">
                                        <label for="nome" class="col-md-4 col-lg-3 col-form-label">Nome
                                            Completo</label>
                                        <div class="col-md-8 col-lg-9">
                                            <input name="nome" type="text" class="form-control" id="fullName"
                                                value="<?= $_SESSION['nome'] ?>">
                                        </div>
                                    </div>

                                    <div class="row mb-3 d-none">
                                        <label for="sobre" class="col-md-4 col-lg-3 col-form-label">Sobre</label>
                                        <div class="col-md-8 col-lg-9">
                                            <textarea name="sobre" class="form-control" id="sobre" style="height: 100px"
                                                placeholder="Faça uma descrição sobre ti"><?= $this->view->user[0]['sobre'] ?></textarea>
                                        </div>
                                    </div>

                                    <div class="row mb-3">
                                        <label for="instituicao"
                                            class="col-md-4 col-lg-3 col-form-label">Instituição</label>
                                        <div class="col-md-8 col-lg-9">
                                            <select class="form-select" id="entidade_" name="instituicao"
                                                onchange="addCurso('')">
                                                <option>Selecinar Entidade</option>
                                                <?php foreach ($this->view->entidade as $value) { ?>
                                                <option>
                                                    <?= $value["nome_inst"] ?>
                                                </option>
                                                <?php } ?>
                                            </select>
                                        </div>
                                    </div>

                                    <div class="row mb-3">
                                        <label for="curso" class="col-md-4 col-lg-3 col-form-label">Curso</label>
                                        <div class="col-md-8 col-lg-9">

                                            <select class="form-select" id="curso_" name="curso"
                                                aria-label="Default select example">
                                                <option selected="">Selecinar Curso</option>

                                            </select>
                                        </div>
                                    </div>

                                    <div class="row mb-3 d-none">
                                        <label for="profisao" class="col-md-4 col-lg-3 col-form-label">Profissão</label>
                                        <div class="col-md-8 col-lg-9">
                                            <input name="profissao" type="text" class="form-control" id="profisao"
                                                placeholder="Ex. Web Designer">
                                        </div>
                                    </div>

                                    <div class="row mb-3">
                                        <label for="telefone" class="col-md-4 col-lg-3 col-form-label">Telefone</label>
                                        <div class="col-md-8 col-lg-9">
                                            <input name="telefone" type="text" class="form-control" id="telefone"
                                                placeholder="(244) 925 283 577"
                                                value=" <?= $this->view->user[0]['telefone'] ?>">
                                        </div>
                                    </div>


                                    <div class="row mb-3">
                                        <label for="Email" class="col-md-4 col-lg-3 col-form-label">Email</label>
                                        <div class="col-md-8 col-lg-9">
                                            <input name="email" type="email" class="form-control"
                                                value=" <?= $this->view->user[0]['email'] ?>" id="Email"
                                                placeholder="k.anderson@example.com">
                                        </div>
                                    </div>

                                    <div class="row mb-3">
                                        <label for="sobre" class="col-md-4 col-lg-3 col-form-label">Sobre</label>
                                        <div class="col-md-8 col-lg-9">
                                            <textarea name="sobre" class="form-control" id="sobre" style="height: 100px"
                                                placeholder="Faça uma descrição sobre ti"><?= $this->view->user[0]['sobre'] ?></textarea>
                                        </div>
                                    </div>

                                    <div class="row mb-3">
                                        <label for="Facebook" class="col-md-4 col-lg-3 col-form-label">Facebook
                                            Profile</label>
                                        <div class="col-md-8 col-lg-9">
                                            <input name="facebook" type="text" class="form-control" id="Facebook"
                                                placeholder="https://facebook.com/#">
                                        </div>
                                    </div>

                                    <div class="row mb-3">
                                        <label for="Linkedin" class="col-md-4 col-lg-3 col-form-label">Linkedin
                                            Profile</label>
                                        <div class="col-md-8 col-lg-9">
                                            <input name="linkedin" type="text" class="form-control" id="Linkedin"
                                                placeholder="https://linkedin.com/#">
                                        </div>
                                    </div>

                                    <div class="text-center">
                                        <button type="submit" class="btn btn-primary">Guardar Alterações</button>
                                    </div>
                                </form><!-- End Profile Edit Form -->

                            </div>

                            <div class="tab-pane fade pt-3" id="profile-settings">

                                <!-- Settings Form -->
                                <form>

                                    <div class="row mb-3">
                                        <label for="fullName" class="col-md-4 col-lg-3 col-form-label">Email
                                            Notifications</label>
                                        <div class="col-md-8 col-lg-9">
                                            <div class="form-check">
                                                <input class="form-check-input" type="checkbox" id="changesMade"
                                                    checked>
                                                <label class="form-check-label" for="changesMade">
                                                    Changes made to your account
                                                </label>
                                            </div>
                                            <div class="form-check">
                                                <input class="form-check-input" type="checkbox" id="newProducts"
                                                    checked>
                                                <label class="form-check-label" for="newProducts">
                                                    Information on new products and services
                                                </label>
                                            </div>
                                            <div class="form-check">
                                                <input class="form-check-input" type="checkbox" id="proOffers">
                                                <label class="form-check-label" for="proOffers">
                                                    Marketing and promo offers
                                                </label>
                                            </div>
                                            <div class="form-check">
                                                <input class="form-check-input" type="checkbox" id="securityNotify"
                                                    checked disabled>
                                                <label class="form-check-label" for="securityNotify">
                                                    Security alerts
                                                </label>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="text-center">
                                        <button type="submit" class="btn btn-primary">Save Changes</button>
                                    </div>
                                </form><!-- End settings Form -->

                            </div>

                            <div class="tab-pane fade pt-3" id="profile-change-password">
                                <!-- Change Password Form -->
                                <form action="/editarSenha" method="post">

                                    <div class="row mb-3">
                                        <label for="currentPassword" class="col-md-4 col-lg-3 col-form-label">Senha
                                            Atual</label>
                                        <div class="col-md-8 col-lg-9">
                                            <input name="password" type="password" class="form-control"
                                                id="currentPassword">
                                        </div>
                                    </div>

                                    <div class="row mb-3">
                                        <label for="newPassword" class="col-md-4 col-lg-3 col-form-label">Nova
                                            Senha</label>
                                        <div class="col-md-8 col-lg-9">
                                            <input name="newpassword" type="password" class="form-control"
                                                id="newPassword">
                                        </div>
                                    </div>

                                    <div class="row mb-3">
                                        <label for="renewPassword" class="col-md-4 col-lg-3 col-form-label">Confirmar
                                            Nova Senha</label>
                                        <div class="col-md-8 col-lg-9">
                                            <input name="renewpassword" type="password" class="form-control"
                                                id="renewPassword">
                                        </div>
                                    </div>

                                    <div class="text-center">
                                        <button type="submit" class="btn btn-primary">Mudar Senha</button>
                                    </div>
                                </form><!-- End Change Password Form -->

                            </div>

                        </div><!-- End Bordered Tabs -->

                    </div>
                </div>

            </div>
        </div>
    </section>

</main><!-- End #main -->