<!DOCTYPE html>
<html lang="en">
<?php

/* error_reporting(0);
 ini_set(“display_errors”, 0 );*/

?>

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>SITA- Sistema Integrado de Trabalhos Académicos</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
        rel="stylesheet">

    <!-- Vendor CSS Files
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  
  <link href="https://cdn.jsdelivr.net/npm/remixicon@2.2.0/fonts/remixicon.css" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" type="text/css">
  -->

    <!-- Vendor CSS Files -->
    <link href="/app/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/app/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="/app/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="/app/assets/vendor/simple-datatables/style.css" rel="stylesheet" type="text/css">

    <script src="app/assets/vendor/pdf/build/pdf.js"></script>
    <script src="app/assets/vendor/pdf/build/pdf.worker.js"></script>

    <!-- Template Main CSS File -->
    <link href="/app/assets/css/style.css" rel="stylesheet">

    <style>
        .container {
            display: flex;
            flex-direction: column;
            justify-content: center;
            background-color: #746e6e;
        }

        .canvas {
            direction: ltr;
            width: 600px;
            margin: auto
        }

        .small,
        small {
            font-size: .875em;
            margin-left: 10px;
            margin-top: -10px;
        }
    </style>
</head>

<body onload="checkAvailiacao(),  previewPdf()" onload="qtdLikesPorProjeto()" id="body">
    <!-- ======= Header ======= -->
    <header id="header" class="header fixed-top d-flex align-items-center">

        <div class="d-flex align-items-center justify-content-between">
            <a href="/homeInst" class="logo d-flex align-items-center">
                <img src="/app/assets/img/logo.png" alt="">
                <span class="d-none d-lg-block">SITA</span>
            </a>
            <i class="bi bi-list toggle-sidebar-btn"></i>
        </div><!-- End Logo -->

        <div class="search-bar">
            <form class="search-form d-flex align-items-center" method="GET" action="/pesquisar">
                <input type="text" name="pesquisar" placeholder="Search" title="Enter search keyword"
                    value="<?= isset($_GET['pesquisar']) ? $_GET['pesquisar'] : "" ?>">
                <button type="submit" title="Search"><i class="bi bi-search"></i></button>
            </form>
        </div><!-- End Search Bar -->

        <nav class="header-nav ms-auto">
            <ul class="d-flex align-items-center">

                <li class="nav-item d-block d-lg-none">
                    <a class="nav-link nav-icon search-bar-toggle " href="#">
                        <i class="bi bi-search"></i>
                    </a>
                </li><!-- End Search Icon-->

                <li class="nav-item dropdown">

                    <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
                        <i class="bi bi-bell"></i>
                        <span class="badge bg-primary badge-number">4</span>
                    </a><!-- End Notification Icon -->

                    <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow notifications">
                        <li class="dropdown-header">
                            You have 4 new notifications
                            <a href="#"><span class="badge rounded-pill bg-primary p-2 ms-2">View all</span></a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li class="notification-item">
                            <i class="bi bi-exclamation-circle text-warning"></i>
                            <div>
                                <h4>Lorem Ipsum</h4>
                                <p>Quae dolorem earum veritatis oditseno</p>
                                <p>30 min. ago</p>
                            </div>
                        </li>

                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li class="notification-item">
                            <i class="bi bi-x-circle text-danger"></i>
                            <div>
                                <h4>Atque rerum nesciunt</h4>
                                <p>Quae dolorem earum veritatis oditseno</p>
                                <p>1 hr. ago</p>
                            </div>
                        </li>

                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li class="notification-item">
                            <i class="bi bi-check-circle text-success"></i>
                            <div>
                                <h4>Sit rerum fuga</h4>
                                <p>Quae dolorem earum veritatis oditseno</p>
                                <p>2 hrs. ago</p>
                            </div>
                        </li>

                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li class="notification-item">
                            <i class="bi bi-info-circle text-primary"></i>
                            <div>
                                <h4>Dicta reprehenderit</h4>
                                <p>Quae dolorem earum veritatis oditseno</p>
                                <p>4 hrs. ago</p>
                            </div>
                        </li>

                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li class="dropdown-footer">
                            <a href="#">Show all notifications</a>
                        </li>

                    </ul><!-- End Notification Dropdown Items -->

                </li><!-- End Notification Nav -->

                <li class="nav-item dropdown">

                    <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
                        <i class="bi bi-chat-left-text"></i>
                        <span class="badge bg-success badge-number">3</span>
                    </a><!-- End Messages Icon -->

                    <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow messages">
                        <li class="dropdown-header">
                            You have 3 new messages
                            <a href="#"><span class="badge rounded-pill bg-primary p-2 ms-2">View all</span></a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li class="message-item">
                            <a href="#">
                                <img src="/app/assets/img/messages-1.jpg" alt="" class="rounded-circle">
                                <div>
                                    <h4>Maria Hudson</h4>
                                    <p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>
                                    <p>4 hrs. ago</p>
                                </div>
                            </a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li class="dropdown-footer">
                            <a href="#">Ver Todas as Mensagens</a>
                        </li>

                    </ul><!-- End Messages Dropdown Items -->

                </li><!-- End Messages Nav -->

                <li class="nav-item dropdown pe-3">

                    <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
                        <img src="/app/assets/img/<?= $_SESSION['img'] ?>" alt="Profile" class="rounded-circle">
                        <span class="d-none d-md-block dropdown-toggle ps-2">
                            <?= $_SESSION['nome'] ?>
                            </< /span>
                    </a><!-- End Profile Iamge Icon -->

                    <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
                        <li class="dropdown-header">
                            <h6>
                                <?= $_SESSION['nome'] ?>
                            </h6><br>
                            <span>Web Designer</span>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li>
                            <a class="dropdown-item d-flex align-items-center" href="users-profile.html">
                                <i class="bi bi-person"></i>
                                <span>Minha Conta</span>
                            </a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li>
                            <a class="dropdown-item d-flex align-items-center" href="users-profile.html">
                                <i class="bi bi-gear"></i>
                                <span>Account Settings</span>
                            </a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li>
                            <a class="dropdown-item d-flex align-items-center" href="pages-faq.html">
                                <i class="bi bi-question-circle"></i>
                                <span>Need Help?</span>
                            </a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li>
                            <a class="dropdown-item d-flex align-items-center" href="/sair">
                                <i class="bi bi-box-arrow-right"></i>
                                <span>Sair</span>
                            </a>
                        </li>

                    </ul><!-- End Profile Dropdown Items -->
                </li><!-- End Profile Nav -->

            </ul>
        </nav><!-- End Icons Navigation -->

    </header><!-- End Header -->
    <!-- ======= Sidebar ======= -->
    <aside id="sidebar" class="sidebar">

        <ul class="sidebar-nav" id="sidebar-nav">
            <li class="nav-heading">Páginas</li>
            <li class="nav-item">
                <a class="nav-link collapsed" href="/homeInst">
                    <i class="bi bi-bank2"></i>
                    <span>Pagina Inicial</span>
                </a>
            </li><!-- End Dashboard Nav -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="/forum">
                    <i class="ri-discuss-fill"></i>
                    <span>Perguntas e Repostas</span>
                </a>
            </li><!-- End Dashboard Nav -->

            <hr>
            <li class="nav-item">
                <a class="nav-link collapsed" href="/salvoInst">
                    <i class="bi bi-grid"></i>
                    <span>Salvo</span>
                </a>
            </li><!-- End Dashboard Nav -->
            <li class="nav-item">
                <a class="nav-link collapsed" data-bs-target="#components-nav" data-bs-toggle="collapse" href="#">
                    <i class="bi bi-menu-button-wide"></i><span>Área de Formação</span><i
                        class="bi bi-chevron-down ms-auto"></i>
                </a>
                <ul id="components-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                    <?php if (count($this->view->universidade) > 0) { ?>
                        <!--========== Árae das Universidades ===========-->
                        <?php foreach ($this->view->universidade as $faculdade) { ?>
                            <li class="nav-item">
                                <a class="nav-link collapsed"
                                    href="/listarCurso?curso=<?= $faculdade['nome_faculdade'] ?>&id_faculdade=<?= $faculdade['id_faculdade'] ?>"
                                    class="text-dark d-block" onclick="addProjetos(<?= $faculdade['id_faculdade'] ?>)">
                                    <i class="bi bi-menu-button-wide"></i><span>
                                        <?= strtoupper($faculdade['nome_faculdade']) ?>
                                    </span><i class="bi bi-chevron-down ms-auto"></i>
                                </a>
                            </li>
                        <?php } ?>
                        <!--========== Fim Árae das Universidades ===========-->
                    <?php } elseif (count($this->view->cursos) > 0) { ?>
                        <!--========== Árae das Faculdades/Centros de Formação ===========-->
                        <?php foreach ($this->view->cursos as $curso) { ?>
                            <li class="nav-item">
                                <a class="nav-link" href="/listarProjetosPorCurso?curso=<?= $curso['nome_curso'] ?>"
                                    onclick="addProjetos(<?= $curso['id'] ?>)">
                                    <i class="bi bi-menu-button-wide"></i><span>
                                        <?= strtoupper($curso['nome_curso']) ?>
                                    </span>
                                </a>
                            </li>
                        <?php } ?>
                        <!--========== Fim Árae das  Faculdades ===========-->
                    <?php } else { ?>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                A definir..
                            </a>
                        </li>
                    <?php } ?>
                </ul>
            </li><!-- End Components Nav -->
            <hr>
            <li class="nav-heading">Assuntos do seu interesse</li>
            <li class="nav-item">
                <a class="nav-link collapsed" href="/editarInst">
                    <i class="bi bi-person"></i>
                    <span>Profile</span>
                </a>
            </li><!-- End Profile Page Nav -->

        </ul>

    </aside><!-- End Sidebar-->

    <?= $this->content() ?>

    <!-- Vendor JS Files 
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/pdfjs-dist@2.14.305/build/pdf.min.js"></script>
  -->
    <script src="/app/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/pdfjs-dist@2.14.305/build/pdf.min.js"></script>

    <!-- Template Main JS File -->
    <script src="/app/assets/js/main.js"></script>
    <script src="/app/assets/js/function.js"></script>
</body>


</html>