<html>
    <head>
      <meta charset="utf-8">
      <meta content="width=device-width, initial-scale=1.0" name="viewport">
    
      <title>SITA - Index</title>
      <meta content="" name="description">
      <meta content="" name="keywords">
    
      <!-- Google Fonts -->
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,600;1,700&family=Poppins:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Inter:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">

      <!-- Vendor CSS Files -->
      <link href="/index/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
      <link href="/index/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
      <link href="/index/assets/vendor/fontawesome-free/css/all.min.css" rel="stylesheet">
      <link href="/index/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
      <link href="/index/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">
      <link href="/index/assets/vendor/aos/aos.css" rel="stylesheet">
    
      <!-- Template Main CSS File -->
      <link href="/index/assets/css/main.css" rel="stylesheet">
    
    </head>

	<body>
       <?= $this->content() ?>
		   <!--Vendor JS Files -->
        <script src="/index/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
        <script src="/index/assets/vendor/purecounter/purecounter_vanilla.js"></script>
        <script src="/index/assets/vendor/glightbox/js/glightbox.min.js"></script>
        <script src="/index/assets/vendor/swiper/swiper-bundle.min.js"></script>
        <script src="/index/assets/vendor/aos/aos.js"></script>
        <script src="/index/assets/vendor/php-email-form/validate.js"></script>
    
        <!-- Template Main JS File -->
        <script src="/index/assets/js/main.js"></script>
        <script src="/index/assets/js/function.js"></script>
	</body>

</html>