<html>

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>SITA - Chat</title>
  <meta content="" name="description">
  <meta content="" name="keywords">
  <link href="/app/assets/vendor/fontawesome/css/font-awesome.min.css" rel="stylesheet
    ">
  <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Montserrat'>
  <link href="/app/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="/chat/style.css">

</head>

<body>
  <?= $this->content() ?>
</body>
<!-- partial -->
<script src="/chat/script.js"></script>

</html>