<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>SITA -
        <?= $this->view->pagina ?>
    </title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
        rel="stylesheet">

    <!-- Vendor CSS Files -->

    <link href="/app/assets/vendor/quill/quill.snow.css" rel="stylesheet">
    <link href="/app/assets/vendor/quill/quill.bubble.css" rel="stylesheet">
    <link href="/app/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/app/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="/app/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="/app/assets/vendor/simple-datatables/style.css" rel="stylesheet" type="text/css">

    <script src="app/assets/vendor/pdf/build/pdf.js"></script>
    <script src="app/assets/vendor/pdf/build/pdf.worker.js"></script>

    <!-- Template Main CSS File -->
    <link href="/app/assets/css/style.css" rel="stylesheet">

    <style>
    .container {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        background-color: #746e6e;
    }

    .canvas {
        direction: ltr;
        width: 90%;
        height: 90%;
        margin: auto
    }
    </style>
</head>

<body onload="checkAvailiacao(), previewPdf()" onload="qtdLikesPorProjeto()">
    <!-- ======= Header ======= -->
    <?php require_once('_components/header_user.php'); ?>
    <!-- ======= Sidebar ======= -->
    <?php require_once('_components/nav_lateral_user.php'); ?>
    <?php if (count($this->view->mentor) == 0) { ?>
    <!-- Modal -->
    <div class="modal fade" id="sejaMentor" tabindex="-1" aria-labelledby="sejaMentorLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="sejaMentorLabel">Torne-se Um Mentor</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form action="/cadastrarMentor" class="row g-3 needs-validation" method="post" novalidate>
                        <div class="mb-3">
                            <label for="validationCustom01" class="form-label">Bilhete de Identidade(PDF ou Uma
                                Imagem)</label>
                            <input type="file" class="form-control" name="bi" id="validationCustom01"
                                aria-label="file example" required>
                            <div class="invalid-feedback">
                                Anexe o seu documento, no formato PDF ou Uma Imagem
                            </div>
                        </div>

                        <div class="col-12">
                            <label for="validationCustom04" class="form-label">Selecine o Tipo de Mentoria</label>
                            <select class="form-select" name="tipo_mentor" id="validationCustom04" required>
                                <option selected disabled value="">Tipo de Mentoria</option>
                                <option>Trabalhos Técnicos</option>
                                <option>Trabalhos Teoricos</option>
                                <option>Ambos</option>
                            </select>
                            <div class="invalid-feedback">
                                Selecione Uma Opção
                            </div>
                        </div>
                        <div class="mb-3">
                            <label for="validationCustom05" class="form-label">Anexe Sua Habilitação Literial</label>
                            <input type="file" class="form-control" name="habilitacao" id="validationCustom05"
                                aria-label="file example" required>
                            <div class="invalid-feedback">Anexe o seu documento, no formato PDF ou Uma Imagem</div>
                        </div>
                        <div class="col-12">
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" value="1" name="condicoes"
                                    id="invalidCheck" required>
                                <label class="form-check-label" for="invalidCheck">
                                    Aceito os Termos e Condições
                                </label>
                                <div class="invalid-feedback">
                                    Vôce deve aceitar os termos
                                </div>
                            </div>
                        </div>

                        <div class="col-12">
                            <button class="btn btn-primary" type="submit">Cadastrar-se</button>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
                </div>
            </div>
        </div>
    </div>
    <!-- Modal -->
    <?php } ?>
    <?= $this->content() ?>
    <!-- ======= Footer ======= -->
    <footer id="footer" class="footer">
        <div class="credits">
            Desenvolvido por <a href="#">Joel Malmba</a> e <a href="#">Josemar Rafael</a>
        </div>
    </footer><!-- End Footer -->

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
            class="bi bi-arrow-up-short"></i></a>

    <script src="/app/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="/app/assets/vendor/apexcharts/apexcharts.min.js"></script>
    <script src="/app/assets/vendor/chart.js/chart.umd.js"></script>
    <script src="/app/assets/vendor/echarts/echarts.min.js"></script>
    <script src="/app/assets/vendor/quill/quill.min.js"></script>
    <script src="/app/assets/vendor/simple-datatables/simple-datatables.js"></script>
    <script src="/app/assets/vendor/tinymce/tinymce.min.js"></script>
    <script src="/app/assets/vendor/php-email-form/validate.js"></script>
    <!-- Template Main JS File -->
    <script src="/app/assets/js/function.js"></script>
    <script src="/app/assets/js/main.js"></script>
    <script>
    // Example starter JavaScript for disabling form submissions if there are invalid fields
    (() => {
        'use strict'

        // Fetch all the forms we want to apply custom Bootstrap validation styles to
        const forms = document.querySelectorAll('.needs-validation')

        // Loop over them and prevent submission
        Array.from(forms).forEach(form => {
            form.addEventListener('submit', event => {
                if (!form.checkValidity()) {
                    event.preventDefault()
                    event.stopPropagation()
                }

                form.classList.add('was-validated')
            }, false)
        })
    })()
    </script>

</body>


</html>