  <main id="main" class="main">

    <div class="pagetitle">
      <h1>Blank Page</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="index.html">Home</a></li>
          <li class="breadcrumb-item">Pages</li>
          <li class="breadcrumb-item active">Blank</li>
        </ol>
      </nav>
    </div><!-- End Page Title -->

    <section class="section dashboard">
      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-body">
              <div class="row">
                <div class="col-md-3">
                   <div class="profile-card pt-4 d-flex flex-column align-items-center" >
                     <img src="/app/assets/img/<?= $_SESSION['img'] ?>" alt="Profile" width="200" height="160" style="border-radius:50%">
                     <h5><?= $_SESSION['nome'] ?></h5>
                     <div class="social-links mt-0 ">
                      <a href="#" style="width:60px;font-size:16px" class="btn btn-sm btn-outline-secondary text-center p-2" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Seguidores">
                        <span class="m-1">4</span>
                        <i class="bi bi-person-plus-fill"></i>
                      </a>
                      <a href="#" style="width:65px;font-size:16px" class="btn btn-sm btn-outline-secondary text-center p-2" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Seguindo">
                        <span class="m-1">14</span>
                        <i class="bi bi-people-fill"></i>
                      </a>
                    </div>
                   </div>
                </div>

                <div class="col-md-8">
                  <h5 class="card-title">Example Card</h5>
                  <p>This is an examle page with no contrnt. You can use it as a starter for your custom pages.</p>
                </div>
              </div>
            </div>
          </div>
        <hr>
        </div>
        
        <div class="col-lg-8">
            <ul class="nav nav-tabs">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="#">Active</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link disabled">Disabled</a>
                </li>
              </ul>

             <div class="d-flex justify-content-center align-items-center"style="height:400px; cursor: pointer;" data-bs-toggle="modal" data-bs-target="#modalDialogScrollable">
                <div class="d-flex flex-column justify-content-center align-items-center" style="border: 1px dashed;border-radius: 3px;height:300px; width: 600px;">
                        <h5>Clique ou Arraste um arquivo(pdf, ppt, docx )</h5>
                        <p>Crie um repositorio para seu projeto </p>
                </div>
               
             </div>
              <!-- Modal Dialog Scrollable -->
              <div class="modal fade" id="modalDialogScrollable" tabindex="-1">
                <div class="modal-dialog modal-dialog-scrollable modal-xl">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title">Modal Dialog Scrollable</h5>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body bg-secodary">
                      <div class="card">
                        <div class="card-body">
                          <h5 class="card-title">General Form Elements</h5>
            
                          <!-- General Form Elements -->
                          <form action="/upload" enctype="multipart/form-data" method="post" >
                            <div class="row mb-3">
                              <label for="inputText" class="col-sm-2 col-form-label">Nome do Projeto</label>
                              <div class="col-sm-10">
                                <input type="text" name="nome" class="form-control">
                              </div>
                            </div>
                            <div class="row mb-3">
                              <label for="inputEmail" class="col-sm-2 col-form-label">Curso</label>
                              <div class="col-sm-10">
                                <input type="text" name="curso" class="form-control">
                              </div>
                            </div>
                            <div class="row mb-3">
                              <label for="inputNumber" class="col-sm-2 col-form-label">Área de Formação</label>
                              <div class="col-sm-10">
                                <input type="text" name="area_formacao" class="form-control">
                              </div>
                            </div>
                            <div class="row mb-3">
                              <label for="inputNumber" class="col-sm-2 col-form-label">File Upload</label>
                              <div class="col-sm-10">
                                <input class="form-control" name="file_upload" type="file" id="formFile">
                              </div>
                            </div>
                            
                            <div class="row mb-3">
                              <label for="inputPassword" class="col-sm-2 col-form-label">Textarea</label>
                              <div class="col-sm-10">
                                <textarea class="form-control" style="height: 100px"></textarea>
                              </div>
                            </div>
                            <fieldset class="row mb-3">
                              <legend class="col-form-label col-sm-2 pt-0">Radio</legend>
                              <div class="col-sm-10">
                                <div class="form-check">
                                  <input class="form-check-input" type="checkbox" name="gridRadios" id="gridRadios2" value="option2">
                                  <label class="form-check-label" for="gridRadios2">
                                    Second radio
                                  </label>
                                </div>
                              </div>
                            </fieldset>
            
                            <div class="row mb-3">
                              <label class="col-sm-2 col-form-label">Select</label>
                              <div class="col-sm-10">
                                <select class="form-select" aria-label="Default select example">
                                  <option selected="">Open this select menu</option>
                                  <option value="1">One</option>
                                  <option value="2">Two</option>
                                  <option value="3">Three</option>
                                </select>
                              </div>
                            </div>
            
                            <div class="row mb-3">
                              <label class="col-sm-2 col-form-label">Submit Button</label>
                              <div class="col-sm-10">
                                <button type="submit" class="btn btn-primary">Submit Form</button>
                              </div>
                            </div>
            
                          </form><!-- End General Form Elements -->
            
                        </div>
                      </div>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    </div>
                  </div>
                </div>
              </div><!-- End Modal Dialog Scrollable-->

        </div>

        <div class="col-lg-4">

         <!-- News & Updates Traffic -->
         <div class="card">
          <div class="filter">
            <a class="icon" href="#" data-bs-toggle="dropdown"><i class="bi bi-three-dots"></i></a>
            <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
              <li class="dropdown-header text-start">
                <h6>Filter</h6>
              </li>

              <li><a class="dropdown-item" href="#">Today</a></li>
              <li><a class="dropdown-item" href="#">This Month</a></li>
              <li><a class="dropdown-item" href="#">This Year</a></li>
            </ul>
          </div>

          <div class="card-body pb-0">
            <h5 class="card-title">News &amp; Updates <span>| Today</span></h5>

            <div class="news">
              <div class="post-item clearfix">
                <img src="/app/assets/img/news-1.jpg" alt="">
                <h4><a href="#">Nihil blanditiis at in nihil autem</a></h4>
                <p>Sit recusandae non aspernatur laboriosam. Quia enim eligendi sed ut harum...</p>
              </div>

              <div class="post-item clearfix">
                <img src="/app/assets/img/news-2.jpg" alt="">
                <h4><a href="#">Quidem autem et impedit</a></h4>
                <p>Illo nemo neque maiores vitae officiis cum eum turos elan dries werona nande...</p>
              </div>

              <div class="post-item clearfix">
                <img src="/app/assets/img/news-3.jpg" alt="">
                <h4><a href="#">Id quia et et ut maxime similique occaecati ut</a></h4>
                <p>Fugiat voluptas vero eaque accusantium eos. Consequuntur sed ipsam et totam...</p>
              </div>

              <div class="post-item clearfix">
                <img src="/app/assets/img/news-4.jpg" alt="">
                <h4><a href="#">Laborum corporis quo dara net para</a></h4>
                <p>Qui enim quia optio. Eligendi aut asperiores enim repellendusvel rerum cuder...</p>
              </div>

              <div class="post-item clearfix">
                <img src="/app/assets/img/news-5.jpg" alt="">
                <h4><a href="#">Et dolores corrupti quae illo quod dolor</a></h4>
                <p>Odit ut eveniet modi reiciendis. Atque cupiditate libero beatae dignissimos eius...</p>
              </div>

            </div><!-- End sidebar recent posts-->

          </div>
        </div><!-- End News & Updates -->

        </div>
    </section>

  </main><!-- End #main -->